"""add_chat_tables

Revision ID: 534e91e27da2
Revises: 65d7416ffbd8
Create Date: 2026-01-17 20:17:58.459642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision: str = '534e91e27da2'
down_revision: Union[str, Sequence[str], None] = '65d7416ffbd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_chats_users_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_created_at'), 'chats', ['created_at'], unique=False)
    op.create_index(op.f('ix_chats_deleted_at'), 'chats', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_chats_is_deleted'), 'chats', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_chats_name'), 'chats', ['name'], unique=False)
    op.create_index(op.f('ix_chats_updated_at'), 'chats', ['updated_at'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_json', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('chat_id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='fk_chat_messages_chats_id_chat', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_chat_id'), 'chat_messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_role'), 'chat_messages', ['role'], unique=False)
    op.create_index(op.f('ix_chat_messages_sequence_number'), 'chat_messages', ['sequence_number'], unique=False)
    op.create_index(op.f('ix_chat_messages_updated_at'), 'chat_messages', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_updated_at'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_sequence_number'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_role'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_chat_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_updated_at'), table_name='chats')
    op.drop_index(op.f('ix_chats_name'), table_name='chats')
    op.drop_index(op.f('ix_chats_is_deleted'), table_name='chats')
    op.drop_index(op.f('ix_chats_deleted_at'), table_name='chats')
    op.drop_index(op.f('ix_chats_created_at'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
